{{- if .Values.dbMigrateJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "csfeer.fullname" . }}-db-migrate
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "csfeer.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "1"
spec:
  restartPolicy: Never
  template:
    metadata:
      labels:
        {{- include "csfeer.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "csfeer.fullname" . }}-db-migrate
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: db-migrate-job-api
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        resources:
          {{- toYaml .Values.dbMigrateJob.resources | nindent 10 }}
        image: "{{ .Values.apiImage.repository }}:{{ .Values.apiImage.tag }}"
        command: ["alembic", "upgrade", "head"]
        env:
          - name: DB_CONFIG__PGUSER
            value: "{{ .Values.dbMigrateJob.env.db_migrate_user_api }}"
        envFrom:
          - configMapRef:
              name: {{ include "csfeer.fullname" . }}-api-config
          - configMapRef:
              name: {{ include "csfeer.fullname" . }}-shared-config

      - name: db-migrate-job-ui
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        resources:
          {{- toYaml .Values.dbMigrateJob.resources | nindent 10 }}
        image: "{{ .Values.uiImage.repository }}:{{ .Values.uiImage.tag }}"
        command: ["python", "manage.py", "migrate"]
        env:
          - name: DB_CONFIG__PGUSER
            value: "{{ .Values.dbMigrateJob.env.db_migrate_user_ui }}"
        envFrom:
          - configMapRef:
              name: {{ include "csfeer.fullname" . }}-ui-config
          - configMapRef:
              name: {{ include "csfeer.fullname" . }}-shared-config
{{- end }}

