# Generated by Django 6.0.4 on 2026-05-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userprofile_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipientUser",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.coreuser",),
        ),
        migrations.AddField(
            model_name="coreuser",
            name="type",
            field=models.CharField(
                choices=[("users.recipientuser", "recipient user")],
                db_index=True,
                default="users.recipientuser",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
