# Generated by Django 6.0.4 on 2026-05-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_recipientuser_coreuser_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="FederalStaffUser",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.coreuser",),
        ),
        migrations.AlterField(
            model_name="coreuser",
            name="type",
            field=models.CharField(
                choices=[
                    ("users.federalstaffuser", "federal staff user"),
                    ("users.recipientuser", "recipient user"),
                ],
                db_index=True,
                max_length=255,
            ),
        ),
    ]
