default_install_hook_types: [pre-commit, commit-msg]

repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.12

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.4
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.408
    hooks:
      - id: pyright

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
        stages: [commit-msg]

  - repo: local
    hooks:
      - id: generate-er-diagrams
        name: Generate ER Diagrams
        entry: make create-erds
        language: system
        files: models\.py$
        pass_filenames: false
