services:
  
  mock-oauth:
    extends:
      file: devops/docker/docker-compose-local.yml
      service: mock-oauth
  
  storage:
    extends:
      file: devops/docker/docker-compose-local.yml
      service: storage
  
  db:
    extends:
      file: devops/docker/docker-compose-local.yml
      service: db

  app:
    extends:
      file: devops/docker/docker-compose-local.yml
      service: app

volumes:
  pgdata:
  storage:
