services:
  
  mock-oauth:
    extends:
      file: devops/docker/docker-compose-local.yml
      service: mock-oauth
  db:
    extends:
      file: devops/docker/docker-compose-local.yml
      service: db

  app:
    extends:
      file: devops/docker/docker-compose-local.yml
      service: app

  app-prod:
    extends:
      file: devops/docker/docker-compose-local.yml
      service: app-prod

  e2e:
    extends:
      file: devops/docker/docker-compose-local.yml
      service: e2e

volumes:
  pgdata:
