services:
  
  mock-oauth:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/csfeerauth
      KC_DB_USERNAME: csfeer
      KC_DB_PASSWORD: secret123
      KC_HTTP_PORT: 8081
      KC_BOOTSTRAP_ADMIN_CLIENT_ID: csfeer-auth
      KC_BOOTSTRAP_ADMIN_CLIENT_SECRET: shhhhhhhh
    command: start-dev --import-realm
    hostname: oauth.csfeer
    healthcheck:
      test: "/bin/true"
    volumes:
      - ./devops/mocks/keycloak:/opt/keycloak/data/import
    depends_on:
      - db
    ports:
      - "127.0.0.1:8081:8081"
    cap_drop:
      - all
    security_opt:
      - "no-new-privileges:true"
  oauth-setup:
    image: quay.io/keycloak/keycloak:latest
    entrypoint: []
    command: bash -c "
      sleep 5 && \
      /opt/keycloak/bin/kcadm.sh config credentials \
        --server http://oauth.csfeer:8081 \
        --realm master \
        --user admin \
        --password admin && \
      /opt/keycloak/bin/kcadm.sh create users \
        -r csfeer \
        -s username=admin \
        -s enabled=true \
        -o --fields id,username \
        -s email=test@gmail.com \
        -s emailVerified=true \
        -s firstName=test \
        -s lastName=test || true && \
      /opt/keycloak/bin/kcadm.sh set-password \
        -r csfeer \
        --username admin \
        --new-password admin && \
      /opt/keycloak/bin/kcadm.sh add-roles \
        -r csfeer \
        --username admin \
        --rolename csfeer_admin \
        --rolename csfeer_user && \
      /opt/keycloak/bin/kcadm.sh update clients/83ab17ea-566c-43b4-abc5-847346d7485a \
        -r csfeer \
        -s \"secret=shhhhhhhh\"
      "
    depends_on:
      - mock-oauth
  db:
    image: postgres:16
    healthcheck:
      test: "/bin/true"
    security_opt:
      - "no-new-privileges:true"
    ports:
      - "5432:5432"
    hostname: db.csfeer
    environment:
      POSTGRES_PASSWORD: secret123
      POSTGRES_USER: csfeer
    volumes:
      - pgdata:/var/lib/postgresql/data
      - "./devops/postgresql/initdb.d:/docker-entrypoint-initdb.d"
    cap_add:
      - DAC_OVERRIDE
      - FOWNER
      - SYS_CHROOT
      - SETGID
      - SETFCAP
      - SETPCAP
      - SETUID
    cap_drop:
      - all

  app:
    build:
      target: dev
    environment:
      OIDC_CONFIG__CLIENT_SECRET: shhhhhhhh
      DB_CONFIG__SSL_MODE: disable
      OIDC_CONFIG__CLIENT_ID: csfeer-auth
      OIDC_CONFIG__DOCUMENT_URL: http://oauth.csfeer:8081/realms/csfeer/.well-known/openid-configuration
      DJANGO_SETTINGS_MODULE: csfeer.settings
      DB_CONFIG__PGHOST: csfeer-db-1
    hostname: ui.csfeer
    post_start:
      - command: "uv run python manage.py migrate"
    security_opt:
      - "no-new-privileges:true"
    ports:
      - "8000:8000"
    healthcheck:
      test: "/bin/true"
    volumes:
      - ./:/app
      - /app/.venv
    depends_on:
      - db
    cap_drop:
      - all

volumes:
  pgdata:
