services:
  
  mock-oauth:
    extends:
      file: ./docker-compose-base.yml
      service: mock-oauth
  db:
    extends:
      file: ./docker-compose-base.yml
      service: db

  storage:
    extends:
      file: ./docker-compose-base.yml
      service: storage

  app:
    build:
      target: dev
      context: ../..
    extends:
      file: ./docker-compose-base.yml
      service: app
    environment:
      - SHOW_APP_VERSION=True
    volumes:
      - ../../csfeer/:/app/csfeer/
      - ../../form_manager/:/app/form_manager/
      - ../../frontend/built/:/app/csfeer/static/frontend/
      - ../../tests:/app/tests/
      - ../../core:/app/core/
      - ../../users:/app/users/
      - ../../organizations:/app/organizations/
      - ../../logs/:/app/logs/

volumes:
  pgdata:
  storage:

