services:
  
  mock-oauth:
    extends:
      file: ./docker-compose-base.yml
      service: mock-oauth
  db:
    extends:
      file: ./docker-compose-base.yml
      service: db

  storage:
    extends:
      file: ./docker-compose-base.yml
      service: storage

  app:
    build:
      target: dev
      context: ../..
    extends:
      file: ./docker-compose-base.yml
      service: app
    environment:
      - SHOW_APP_VERSION=True
      - ALLOW_ADMIN_AUTHENTICATION=True
    post_start:
      - command: >
          /bin/bash -c "
          uv run python manage.py migrate --noinput &&
          uv run manage.py seed_test_users &&
          uv run manage.py load_initial_forms
          "
    volumes:
      - ../../csfeer/:/app/csfeer/
      - ../../form_manager/:/app/form_manager/
      - ../../frontend/built/:/app/csfeer/static/frontend/
      - ../../tests:/app/tests/
      - ../../core:/app/core/
      - ../../users:/app/users/
      - ../../organizations:/app/organizations/
      - ../../logs/:/app/logs/
      - ../../.coverage_report/:/app/.coverage_report/

volumes:
  pgdata:
  storage:

