services:
  
  mock-oauth:
    extends:
      file: ./docker-compose-base.yml
      service: mock-oauth
  db:
    extends:
      file: ./docker-compose-base.yml
      service: db

  app:
    environment:
      DB_CONFIG__pgdatabase: csfeer_e2e_test
      DB_CONFIG__test_pgdatabase: csfeer_e2e_test
    image: "${IMAGE_NAME}"
    extends:
      file: ./docker-compose-base.yml
      service: app
    volumes:
      - ../../csfeer/:/app/csfeer/
      - ../../form_manager/:/app/form_manager/
      - ../../django_cotton_uswds/:/app/django_cotton_uswds/
      - ../../frontend/built/:/app/csfeer/static/frontend/
      - ../../tests:/app/tests/
    post_start:
      - command: "uv run python manage.py seed_e2e_users"
      - command: "uv run python manage.py seed_demo_org --all"
      - command: "uv run python manage.py load_initial_forms"
  e2e:
    image: "${IMAGE_NAME}"
    extends:
      file: ./docker-compose-base.yml
      service: e2e

volumes:
  pgdata:
