# Generated by Django 6.0.4 on 2026-05-21 15:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("form_manager", "0007_alter_formentry_options_formaudittrail_rationale_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FormReturn",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("returned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="Optional summary note that opens the recipient notification email (CORE-42).",
                    ),
                ),
                ("ao_signature_cleared", models.BooleanField(default=False)),
                (
                    "form_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_returns",
                        to="form_manager.formentry",
                    ),
                ),
                (
                    "returned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="returns_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-returned_at"],
                "permissions": [("view_any_return", "View any submission return record")],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FormReturnItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("section", models.CharField(blank=True, max_length=200)),
                ("field", models.CharField(blank=True, max_length=200)),
                (
                    "text",
                    models.TextField(
                        help_text="The review-item description shown to the recipient."
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Display order within the return."
                    ),
                ),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "acknowledgement_response",
                    models.TextField(
                        blank=True,
                        help_text="Recipient's reply text shown to staff when reviewing the resubmission.",
                    ),
                ),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="return_items_acknowledged",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "form_return",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="staff_review.formreturn",
                    ),
                ),
            ],
            options={
                "ordering": ["form_return", "order"],
                "abstract": False,
            },
        ),
    ]
