# Generated by Django 6.0.4 on 2026-05-21 17:34

import django.db.models.deletion
import staff_review.audit_models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff_review", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountAuditTrail",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("user_created", "User created"),
                            ("user_deactivated", "User deactivated"),
                            ("user_reactivated", "User reactivated"),
                            ("group_added", "Group / role added"),
                            ("group_removed", "Group / role removed"),
                            ("org_membership_added", "Organization membership added"),
                            ("org_membership_removed", "Organization membership removed"),
                            ("permission_added", "Permission granted"),
                            ("permission_removed", "Permission revoked"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Free-form context per action: e.g., {'group':'Federal Staff'} or {'org_id':'<uuid>'}.",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who initiated the change. NULL = system / migration.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="account_audit_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        help_text="The user whose account changed.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["target_user", "-created_at"], name="staff_revie_target__df34e1_idx"
                    ),
                    models.Index(
                        fields=["actor", "-created_at"], name="staff_revie_actor_i_9fc83a_idx"
                    ),
                    models.Index(fields=["action"], name="staff_revie_action_7aa502_idx"),
                ],
            },
            bases=(staff_review.audit_models.ImmutableAuditMixin, models.Model),
        ),
        migrations.CreateModel(
            name="SystemEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("login_failed", "Login failed"),
                            ("export_csv", "CSV export downloaded"),
                            ("audit_log_viewed", "Audit log viewed"),
                        ],
                        max_length=40,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=512)),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="system_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["kind", "-created_at"], name="staff_revie_kind_542a8d_idx"
                    ),
                    models.Index(
                        fields=["actor", "-created_at"], name="staff_revie_actor_i_9d488d_idx"
                    ),
                ],
            },
            bases=(staff_review.audit_models.ImmutableAuditMixin, models.Model),
        ),
    ]
