# Generated by Django 6.0 on 2026-04-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("organizations", "0001_add_organization_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="userorganizationmembership",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The permission group that the user belongs to for this organization",
                related_name="org_memberships",
                to="auth.group",
            ),
        ),
        migrations.AddField(
            model_name="userorganizationmembership",
            name="permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions individually assigned to this user for this organization in addition to those assiged by any permission groups",
                related_name="org_memberships",
                to="auth.permission",
            ),
        ),
    ]
