# Generated by Django 6.0 on 2026-04-24 14:50
"""Create the known permission groups and assign the specific permissions to each group"""

import logging
from django.db import migrations

try:
    from users.permissions import ORG_PERMISSION_GROUPS
except ImportError:
    ORG_PERMISSION_GROUPS = {}


def create_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    for group_name, codenames in ORG_PERMISSION_GROUPS.items():
        group, created = Group.objects.get_or_create(name=group_name)
        permissions = Permission.objects.filter(codename__in=codenames)
        group.permissions.set(permissions)


def delete_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__in=ORG_PERMISSION_GROUPS.keys()).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("form_manager", "0004_alter_formentry_options"),
        ("organizations", "0002_userorganizationmembership_groups_and_more"),
    ]

    operations = [
        migrations.RunPython(create_groups, delete_groups),
    ]
