# Generated by Django 6.0 on 2026-04-24 14:50
"""Create the known permission groups and assign the specific permissions to each group"""

from django.db import migrations


groups_to_create = {
    "Recipient Form Viewer": ["form_view"],
    "Recipient Form Editor": ["form_view", "form_start", "form_edit"],
    "Recipient Form Approver": ["form_view", "form_start", "form_edit", "form_submit"],
    "Recipient Authorized Official": [
        "form_view",
        "form_start",
        "form_edit",
        "form_submit",
        "form_tribal_plan_can_sign_authorized_official",
    ],
}


def create_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    for group_name, codenames in groups_to_create.items():
        group, _ = Group.objects.get_or_create(name=group_name)
        permissions = Permission.objects.filter(codename__in=codenames)
        group.permissions.set(permissions)


def delete_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__in=groups_to_create.keys()).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("form_manager", "0004_alter_formentry_options"),
        ("organizations", "0002_userorganizationmembership_groups_and_more"),
    ]

    operations = [
        migrations.RunPython(create_groups, delete_groups),
    ]
