# Generated by Django 6.0 on 2026-04-24 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_auto_20260424_1050"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userorganizationmembership",
            name="role",
        ),
    ]
