# Generated by Django 6.0.4 on 2026-05-08 14:48

import django.db.models.deletion
import localflavor.us.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_remove_userorganizationmembership_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="userorganizationmembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    localflavor.us.models.USStateField(
                        max_length=2, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("Region 1", "Region 1"),
                            ("Region 4", "Region 4"),
                            ("Region 5", "Region 5"),
                            ("Region 6", "Region 6"),
                            ("Region 7", "Region 7"),
                            ("Region 8", "Region 8"),
                            ("Region 9", "Region 9"),
                            ("Region 10", "Region 10"),
                        ]
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(fields=["region"], name="organizatio_region_35624e_idx"),
                    models.Index(fields=["region", "code"], name="organizatio_region_527347_idx"),
                ],
            },
        ),
    ]
