# Generated by Django 6.0.4 on 2026-05-08 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0006_populate_states"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationprofile",
            name="state",
            field=models.ForeignKey(
                default="MA",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="organizations",
                to="organizations.state",
            ),
            preserve_default=False,
        ),
    ]
