# Generated by Django 6.0.4 on 2026-05-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0008_populate_organizations"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationprofile",
            name="org_type",
            field=models.CharField(
                choices=[
                    ("tribe", "Federally Recognized Tribe"),
                    ("tribal_org", "Tribal Organization"),
                    ("state", "State Government"),
                    ("territory", "U.S. Territory"),
                    ("higher_ed", "Higher Education Institution"),
                    ("workforce_agency", "Workforce System Agency"),
                    ("cbo", "Community-Based Organization"),
                    ("faith_based", "Faith-Based Organization"),
                    ("other", "Other"),
                ],
                default="tribe",
                help_text="STAFF-MP-02: Tribal / State / Territory / CBO / Higher Ed / etc.",
                max_length=30,
            ),
        ),
    ]
