{{- if .Values.pythonShell.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "csfeer.fullname" . }}-python-shell
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "csfeer.labels" . | nindent 4 }}
    app.kubernetes.io/component: python-shell
spec:
  replicas: 1
  revisionHistoryLimit: 1 # Keep at least 1 revisions of the deployment
  selector:
    matchLabels:
      {{- include "csfeer.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: python-shell
  template:
    metadata:
      labels:
        {{- include "csfeer.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: python-shell
    spec:
      serviceAccountName: {{ include "csfeer.fullname" . }}-python-shell
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: python-shell
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          image: {{ .Values.pythonShell.repository }}:{{ .Values.pythonShell.tag }}
          imagePullPolicy: {{ .Values.pythonShell.pullPolicy }}
          command: ["/bin/bash", "-c"]
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - '-c'
                - echo ready
            failureThreshold: 3
            initialDelaySeconds: 2
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 2
          args: ["while true; do sleep 30; done"]
          resources:
            {{- toYaml .Values.pythonShell.resources | nindent 12 }}
{{- end }} 