apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csfeer-dev # Change this to the correct environment 
  namespace: argocd
spec:
  destination:
    namespace: csfeer-dev # Change this to the correct environment
    server: "https://kubernetes.default.svc"
  source:
    repoURL: FILL IN
    targetRevision: FILL IN # Change this to the correct version i.e. 1.2.0+7083dea7
    chart: csfeer
    helm: 
      valueFiles: # Order of value files is important, the first value file should always be the values.yaml file
        - values.yaml
        - values-dev.yaml
        

  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
