"""
Django settings for csfeer project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from .config import AppConfig

settings = AppConfig()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-sjad)=8ant$2q45t2tf$(tpy0xs6ggk@18&h67b)=6qtj6!em-"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party
    "oauth2_authcodeflow",
    "pattern_library",
    "crispy_forms",
    "django_cotton",
    "django_extensions",
    # Local
    "form_manager",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "oauth2_authcodeflow.middleware.LoginRequiredMiddleware",
    "oauth2_authcodeflow.middleware.RefreshAccessTokenMiddleware",
    "oauth2_authcodeflow.middleware.RefreshSessionMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

AUTHENTICATION_BACKENDS = ["oauth2_authcodeflow.auth.AuthenticationBackend"]
ROOT_URLCONF = "csfeer.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "csfeer", "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
            "builtins": ["pattern_library.loader_tags"],
        },
    },
]

CRISPY_TEMPLATE_PACK = "uswds"
CRISPY_ALLOWED_TEMPLATE_PACKS = ("uni_form", "uswds")

STATIC_URL = "/static/"
STATICFILES_FINDERS = [
    "npm.finders.NpmFinder",
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]
STATICFILES_DIRS = [
    BASE_DIR / "csfeer" / "static",  # Where Django looks for static files
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"
NPM_ROOT_PATH = str(BASE_DIR / "csfeer")  # Where your package.json is located
NPM_FILE_PATTERNS = {
    "@uswds/uswds": [
        "dist/css/*.css",
        "dist/js/*.js",
        "dist/js/*.map",
        "dist/fonts/**/*",
        "dist/img/**/*",
    ],
    "alpinejs": ["dist/*.js"],
    "htmx.org": ["dist/*.js"],
    "htmx-ext-sse": ["dist/*.js"],
}

WSGI_APPLICATION = "csfeer.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "csfeer.postgresql",
        "NAME": settings.db_config.pgdatabase,
        "CONN_MAX_AGE": 60 * 14,  # IAM password tokens only last 15 minutes
        "CONN_HEALTH_CHECKS": True,
        "POOL": True,
        "OPTIONS": {
            "sslmode": settings.db_config.ssl_mode,
            "options": f"-c statement_timeout={settings.db_config.statement_timeout}",
        },
    }
}

# Django App Configuration
SECRET_KEY = settings.secret_key
DEBUG = settings.debug
ALLOWED_HOSTS = settings.allowed_hosts
LANGUAGE_CODE = settings.language_code
TIME_ZONE = settings.time_zone
USE_I18N = settings.use_i18n
USE_TZ = settings.use_tz

# OIDC Configuration
OIDC_OP_DISCOVERY_DOCUMENT_URL = settings.oidc_config.document_url
OIDC_RP_CLIENT_ID = settings.oidc_config.client_id
OIDC_RP_CLIENT_SECRET = settings.oidc_config.client_secret
OIDC_RP_FORCE_SECRET_WITH_PKCE = settings.oidc_config.force_secret_with_pkce
OIDC_RP_SCOPES = settings.oidc_config.scopes
OIDC_MIDDLEWARE_NO_AUTH_URL_PATTERNS = settings.oidc_config.no_auth_urls
OIDC_EXTEND_USER = "csfeer.auth.extend_user_with_roles"

PATTERN_LIBRARY = {
    "SECTIONS": (
        ("Components", ["patterns/components"]),
        ("Pages", ["patterns/pages"]),
    ),
    "TEMPLATE_SUFFIX": ".html",
    "PATTERN_BASE_TEMPLATE_NAME": "patterns/base.html",
}

if DEBUG:
    X_FRAME_OPTIONS = "SAMEORIGIN"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
