apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/part-of: keycloak

spec:
  project: default
  source:
    repoURL: FILL IN
    chart: FILL IN
    targetRevision: 25.0.1
    helm:
      parameters:
        # Global settings
        - name: global.imageRegistry
          value: "FILL IN"
        - name: global.security.allowInsecureImages
          value: "true"
        
        #  image
        - name: image.registry
          value: "FILL IN"
        - name: image.repository
          value: "FILL IN"
        
        # psql settings
        - name: postgresql.enabled
          value: "true"
        - name: postgresql.image.registry
          value: "FILL IN"
        - name: postgresql.image.repository
          value: "FILL IN"
        - name: postgresql.image.tag
          value: "17.6.0-debian-12-r0"
        - name: postgresql.auth.username
          value: "bn_keycloak"
        - name: postgresql.auth.password
          value: "keycloak-db-password"
        - name: postgresql.auth.database
          value: "bitnami_keycloak"
        - name: postgresql.auth.postgresPassword
          value: "postgres-admin-password"
        
        # Keycloak auth
        - name: auth.adminUser
          value: "admin"
        - name: auth.adminPassword
          value: "changeme"
        
        # ALB settings
        - name: production
          value: "false"
        - name: proxyHeaders
          value: "xforwarded"
        
        # Ingress settings
        - name: ingress.enabled
          value: "true"
        - name: ingress.hostname
          value: "FILL IN"
        - name: ingress.ingressClassName
          value: "alb"
        - name: ingress.annotations.alb\.ingress\.kubernetes\.io/scheme
          value: "internal"
        - name: ingress.annotations.alb\.ingress\.kubernetes\.io/target-type
          value: "ip"
        - name: ingress.annotations.alb\.ingress\.kubernetes\.io/listen-ports
          value: '[{"HTTP": 80}]'
        - name: ingress.annotations.alb\.ingress\.kubernetes\.io/load-balancer-name
          value: "keycloak-alb"

  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
