{{- if .Values.externalSecrets -}}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ include "csfeer.fullname" . }}-cluster-secret-store
  labels:
    {{- include "csfeer.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.externalSecrets.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "csfeer.fullname" . }}
            namespace: {{ .Release.Namespace }}
{{- end }} 