apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "csfeer.fullname" . }}-app-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "csfeer.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/load-balancer-attributes: >-
      deletion_protection.enabled={{ .Values.service.app.deletionProtectionEnabled }},
      routing.http.drop_invalid_header_fields.enabled=true,
      access_logs.s3.enabled=true,
      access_logs.s3.bucket={{ .Values.service.app.loadBalancerLoggingBucket }},
      access_logs.s3.prefix=access-logs,
      connection_logs.s3.enabled=true,
      connection_logs.s3.bucket={{ .Values.service.app.loadBalancerLoggingBucket }},  
      connection_logs.s3.prefix=connection-logs
    alb.ingress.kubernetes.io/load-balancer-name: {{ include "csfeer.fullname" . }}-app-alb
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/manage-backend-security-group-rules: 'true'
    alb.ingress.kubernetes.io/scheme: {{ .Values.service.app.scheme | default "internal" }}
    alb.ingress.kubernetes.io/target-type: ip
    {{- if .Values.service.app.enableSSL }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.service.app.sslCertArn }}
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-2021-06
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    {{- else }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    {{- end }}
    {{- if .Values.service.app.subnets }}
    alb.ingress.kubernetes.io/subnets: {{ .Values.service.app.subnets | join "," }}
    {{- end }}
    {{- if .Values.service.app.securityGroups }}
    alb.ingress.kubernetes.io/security-groups: {{ .Values.service.app.securityGroups | join "," }}
    {{- end }}
    {{- if .Values.service.app.securityGroupPrefixLists }}
    alb.ingress.kubernetes.io/security-group-prefix-lists: "{{ .Values.service.app.securityGroupPrefixLists | join "," }}"
    {{- end }}
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "csfeer.fullname" . }}-app-service
                port:
                  number: {{ .Values.service.app.targetPort | default 8080 }}