# Generated by Django 6.0 on 2026-02-05 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("form_manager", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formauditdetail",
            name="timestamp",
        ),
        migrations.RemoveField(
            model_name="formaudittrail",
            name="timestamp",
        ),
    ]
