# Generated by Django 5.2.7 on 2025-11-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formdefinition",
            name="code",
            field=models.CharField(
                db_index=True,
                help_text="A unique identifier for this form definition, like an OMB form number.",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="formdefinition",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
