# Generated by Django 5.2.7 on 2025-11-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form_manager", "0002_alter_formdefinition_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="formdefinition",
            name="schema_class",
            field=models.CharField(
                default="TribalShortForm",
                help_text="The name of the pydantic form schema class",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
