# Generated by Django 5.2.7 on 2025-11-25 16:46

from django.db import migrations, models

import form_manager.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("form_manager", "0003_formdefinition_schema_class"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="formdefinition",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="formdefinition",
            name="family",
            field=models.CharField(
                choices=[("0970-0492", "CSBG Annual Report")],
                default="foo",
                help_text="The name of the form family",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="formdefinition",
            name="name",
            field=models.CharField(
                choices=[
                    ("CSBG Annual Report 2.1 (Eligible Entities)", "Entities Annual Report 2 1"),
                    ("CSBG Annual Report 2.1 (States)", "States Annual Report 2 1"),
                    ("CSBG Annual Report 3.0 (Eligible Entities)", "Entitites Annual Report 3 0"),
                    ("CSBG Annual Report 3.0 (States)", "States Annual Report 3 0"),
                    (
                        "CSBG Annual Report 3.0 Tribal Annual Report (Tribes)",
                        "Tribal Annual Report 3 0",
                    ),
                    (
                        "CSBG Annual Report 3.0 Tribal Short Form (Tribes)",
                        "Tribal Annual Report 3 0 Short",
                    ),
                ],
                default="foo",
                help_text="The official name of the form.",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="formdefinition",
            name="variant",
            field=form_manager.models.fields.SemVerField(
                default="1.0.0",
                help_text="The internal variant number of a form definition",
                max_length=20,
            ),
        ),
        migrations.RemoveField(
            model_name="formdefinition",
            name="code",
        ),
        migrations.RemoveField(
            model_name="formdefinition",
            name="title",
        ),
        migrations.RemoveField(
            model_name="formdefinition",
            name="version",
        ),
    ]
