# Generated by Django 6.0 on 2026-04-24 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("form_manager", "0003_remove_organization_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="formentry",
            options={
                "ordering": ["-updated_at"],
                "permissions": [
                    ("form_view", "Can view a form instance"),
                    ("form_edit", "Can edit a form instance"),
                    ("form_submit", "Can submit a form instance"),
                    (
                        "form_tribal_plan_can_sign_authorized_official",
                        "Can sign the Authorized Official page of the tribal plan form",
                    ),
                ],
            },
        ),
    ]
