# Generated by Django 5.2.7 on 2025-11-25 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("form_manager", "0004_alter_formdefinition_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="formdefinition",
            unique_together={("name", "variant")},
        ),
    ]
