# Generated by Django 6.0 on 2026-04-28 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("form_manager", "0004_alter_formentry_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="formdefinition",
            options={
                "permissions": [
                    ("form_list", "Can see this form in the forms list page"),
                    ("form_start", "Can start a form instance"),
                ]
            },
        ),
    ]
