# Generated by Django 6.0.4 on 2026-05-21 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form_manager", "0006_add_formeditinglock"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="formentry",
            options={
                "ordering": ["-updated_at"],
                "permissions": [
                    ("form_view", "Can view a form instance"),
                    ("form_edit", "Can edit a form instance"),
                    ("form_submit", "Can submit a form instance"),
                    (
                        "form_tribal_plan_can_sign_authorized_official",
                        "Can sign the Authorized Official page of the tribal plan form",
                    ),
                    (
                        "staff_view_any_submission",
                        "Federal Staff -- view any submission regardless of region (CORE-29, CORE-132)",
                    ),
                    (
                        "staff_edit_on_behalf",
                        "Federal Staff -- edit any submission on behalf of recipient (CORE-167)",
                    ),
                    (
                        "staff_return_submission",
                        "Federal Staff -- return a submission with review items (CORE-168, CORE-169)",
                    ),
                    (
                        "staff_determine_submission",
                        "Federal Staff -- record final determination (Accept / Close) (CORE-44, CORE-45)",
                    ),
                    (
                        "staff_archive_submission",
                        "Federal Staff -- archive a submission (CORE-132)",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="formaudittrail",
            name="rationale",
            field=models.TextField(
                blank=True,
                help_text="Required for edit_on_behalf actions per CORE-167. Immutable after save.",
            ),
        ),
        migrations.AddField(
            model_name="formentry",
            name="determination_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="formentry",
            name="determination_outcome",
            field=models.CharField(
                blank=True,
                choices=[("accepted", "Accepted"), ("closed", "Closed without Acceptance")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="formentry",
            name="determined_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="formentry",
            name="determined_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="determined_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="formentry",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("in_progress", "In Progress"),
                    ("returned", "Returned"),
                    ("amended", "Amended"),
                    ("accepted", "Accepted"),
                    ("closed", "Closed without Acceptance"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
