# Generated by Django 6.0.4 on 2026-05-18 01:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form_manager", "0006_add_formeditinglock"),
    ]

    operations = [
        migrations.AddField(
            model_name="formentry",
            name="fiscal_year",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Federal FY ending calendar year, e.g. 2025 for FY25",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="SubmissionWindow",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "fiscal_year",
                    models.PositiveSmallIntegerField(
                        help_text="FY ending calendar year, e.g. 2025 for FY25"
                    ),
                ),
                (
                    "opens_at",
                    models.DateField(
                        blank=True,
                        help_text="Defaults to Oct 1 of the prior calendar year if left blank.",
                    ),
                ),
                (
                    "closes_at",
                    models.DateField(
                        blank=True,
                        help_text="Defaults to Sep 30 of the FY ending year if left blank.",
                    ),
                ),
                (
                    "form_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submission_windows",
                        to="form_manager.formdefinition",
                    ),
                ),
            ],
            options={
                "ordering": ["-fiscal_year", "form_definition__name"],
                "abstract": False,
                "unique_together": {("form_definition", "fiscal_year")},
            },
        ),
    ]
