# Generated by Django 6.0.4 on 2026-05-21 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form_manager", "0007_alter_formentry_options_formaudittrail_rationale_and_more"),
        ("programs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="formdefinition",
            name="cycle_type",
            field=models.CharField(
                choices=[
                    ("annual", "Annual"),
                    ("quarterly", "Quarterly"),
                    ("monthly", "Monthly"),
                    ("ad_hoc", "Ad-hoc"),
                ],
                default="annual",
                help_text="Submission cycle frequency (STAFF-MP-03). CSBG = annual; ACF-196R = quarterly.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="formdefinition",
            name="is_shared",
            field=models.BooleanField(
                default=False,
                help_text="True for cross-program shared forms like SF-424 (STAFF-MP-06).",
            ),
        ),
        migrations.AddField(
            model_name="formdefinition",
            name="program",
            field=models.ForeignKey(
                blank=True,
                help_text="The ACF program this form belongs to (STAFF-MP-01). Existing rows backfill to CSBG.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="form_definitions",
                to="programs.program",
            ),
        ),
    ]
