# Generated by Django 6.0.4 on 2026-05-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form_manager", "0007_add_submission_window"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formentry",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("amended", "Amended"),
                    ("archived", "Archived"),
                    ("closed_without_acceptance", "Closed without acceptance"),
                ],
                default="draft",
                max_length=32,
            ),
        ),
    ]
