# Generated by Django 6.0.4 on 2026-05-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form_manager", "0009_alter_formdefinition_family_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formdefinition",
            name="family",
            field=models.CharField(
                choices=[
                    ("0970-0492", "CSBG Annual Report"),
                    ("0970-0635", "CSBG Model Tribal Plan Applications"),
                    ("0970-0382", "CSBG State and Territory Plan"),
                    ("0970-0408", "CSBG Eligible Entity List"),
                    ("0970-0080", "LIHEAP Performance Data Form"),
                    ("0970-0567", "LIHWAP Performance Data Form"),
                    ("0970-0202", "Assets for Independence (AFI) Annual Report"),
                    ("0970-0386", "Community Economic Development (CED) Performance Report"),
                    ("0970-0234", "SSBG Annual Report (SF-PPR)"),
                    ("0970-RCD", "Rural Community Development Performance Report"),
                    ("0970-0338", "TANF ACF-196R Financial Report"),
                    ("0970-0345", "Tribal TANF Data Report"),
                    ("0970-0460", "HMRF Performance Progress Report"),
                    ("0970-0394", "HPOG Performance Progress Report (dormant)"),
                ],
                help_text="The name of the form family",
            ),
        ),
        migrations.AlterField(
            model_name="formdefinition",
            name="name",
            field=models.CharField(
                choices=[
                    ("CSBG Annual Report 2.1 (Eligible Entities)", "Entities Annual Report 2 1"),
                    ("CSBG Annual Report 2.1 (States)", "States Annual Report 2 1"),
                    ("CSBG Annual Report 3.0 (Eligible Entities)", "Entitites Annual Report 3 0"),
                    ("CSBG Annual Report 3.0 (States)", "States Annual Report 3 0"),
                    (
                        "CSBG Annual Report 3.0 Tribal Annual Report (Tribes)",
                        "Tribal Annual Report 3 0",
                    ),
                    (
                        "CSBG Annual Report 3.0 Tribal Short Form (Tribes)",
                        "Tribal Annual Report 3 0 Short",
                    ),
                    ("CSBG Model Tribal Plan", "Csbg Tribal Plan"),
                    ("CSBG State Plan", "Csbg State Plan"),
                    ("CSBG Territory Plan", "Csbg Territory Plan"),
                    ("CSBG Eligible Entity List", "Csbg Eligible Entity List"),
                    ("LIHEAP Model State / Tribal Plan", "Liheap Model Plan"),
                    ("LIHEAP Performance Data Form", "Liheap Performance Data Form"),
                    ("LIHEAP Household Report", "Liheap Household Report"),
                    ("LIHWAP Performance Data Form", "Lihwap Performance Data Form"),
                    ("LIHWAP Quarterly Drawdown Report", "Lihwap Quarterly Drawdown"),
                    ("AFI Annual Report", "Afi Annual Report"),
                    ("AFI Project Application", "Afi Project Application"),
                    ("CED Project Application", "Ced Application"),
                    ("CED Performance Progress Report", "Ced Performance Progress Report"),
                    ("CED Final Performance Report", "Ced Final Performance Report"),
                    ("RCD Project Application", "Rcd Application"),
                    ("RCD Annual Performance Report", "Rcd Performance Report"),
                    ("SSBG Annual Report (SF-PPR)", "Ssbg Annual Report"),
                    ("SSBG Pre-Expenditure Report", "Ssbg Pre Expenditure Report"),
                    ("TANF ACF-196R Financial Report", "Tanf Acf 196R"),
                    ("TANF ACF-199 Data Report", "Tanf Acf 199"),
                    ("TANF MOE Annual Report", "Tanf Moe Report"),
                    ("Tribal TANF Data Report (ACF-343)", "Tribal Tanf Data"),
                    ("Tribal TANF Plan", "Tribal Tanf Plan"),
                    ("HMRF Performance Progress Report", "Hmrf Ppr"),
                    ("HMRF Final Performance Report", "Hmrf Final Report"),
                    ("HPOG Performance Progress Report", "Hpog Ppr"),
                ],
                help_text="The official name of the form.",
                max_length=255,
            ),
        ),
    ]
