# Generated by Django 6.0.4 on 2026-06-03 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form_manager", "0010_extend_form_name_choices_for_ofa"),
    ]

    operations = [
        migrations.AddField(
            model_name="formdefinition",
            name="draft_schema",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="formdefinition",
            name="draft_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
