# Generated by Django 6.0.4 on 2026-05-21 17:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form_manager", "0008_formdefinition_cycle_type_formdefinition_is_shared_and_more"),
        ("organizations", "0009_organizationprofile_org_type"),
        ("programs", "0002_seed_acf_programs"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormScoping",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "scope_to_org_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of OrgType values: forms apply to all orgs of these types. Empty list = no rule (only explicit_orgs apply).",
                    ),
                ),
                (
                    "explicit_orgs",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Additional specific orgs in scope, regardless of org_type rule.",
                        related_name="scoped_forms",
                        to="organizations.organizationprofile",
                    ),
                ),
                (
                    "form_definition",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoping",
                        to="form_manager.formdefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Form scoping",
                "verbose_name_plural": "Form scopings",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SubmissionWindow",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "fiscal_year",
                    models.CharField(
                        help_text="e.g., 'FY26', 'FY26-Q1'. Format is program-conventional.",
                        max_length=10,
                    ),
                ),
                (
                    "opens_at",
                    models.DateTimeField(
                        help_text="When recipients can start new drafts. Before this -> Upcoming."
                    ),
                ),
                (
                    "closes_at",
                    models.DateTimeField(
                        help_text="After this, no new drafts. Existing drafts may still be edited + submitted per CORE-25."
                    ),
                ),
                (
                    "form_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submission_windows",
                        to="form_manager.formdefinition",
                    ),
                ),
            ],
            options={
                "ordering": ["form_definition", "-opens_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["form_definition", "fiscal_year"],
                        name="programs_su_form_de_32f441_idx",
                    ),
                    models.Index(fields=["opens_at"], name="programs_su_opens_a_a48b85_idx"),
                    models.Index(fields=["closes_at"], name="programs_su_closes__492a56_idx"),
                ],
                "unique_together": {("form_definition", "fiscal_year")},
            },
        ),
    ]
