apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "csfeer.fullname" . }}-app-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "csfeer.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "0"
data:
{{- range $key, $value := .Values.configMap.app }}
  {{ $key }}: {{ $value | quote }}
{{- end }} 