apiVersion: v1
kind: Service
metadata:
  name: {{ include "csfeer.fullname" . }}-app-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "csfeer.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.app.targetPort | default 8080 }}
      targetPort: {{ .Values.service.app.targetPort | default 8080 }}
      protocol: TCP
  selector:
    {{- include "csfeer.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: app