from typing import Generic

from django import forms

from form_manager.schema.widgets import YesNoDisplayWidget

class EmailStr(str): ...

class ACFFieldMixin:
    title: str | None
    description: str | None
    review_title: str | None
    is_presentational_only: bool = False
    def __init__(self, *args, title=None, description=None, **kwargs) -> None: ...

class ACFFieldsMeta(type):
    def __new__(cls, name, bases=(), dct={}): ...

class ACFField(ACFFieldMixin, forms.Field): ...
class ACFCharField(ACFFieldMixin, forms.CharField): ...
class ACFIntegerField(ACFFieldMixin, forms.IntegerField): ...
class ACFFloatField(ACFFieldMixin, forms.FloatField): ...
class ACFDecimalField(ACFFieldMixin, forms.DecimalField): ...
class ACFDateField(ACFFieldMixin, forms.DateField): ...
class ACFTimeField(ACFFieldMixin, forms.TimeField): ...
class ACFDateTimeField(ACFFieldMixin, forms.DateTimeField): ...
class ACFDurationField(ACFFieldMixin, forms.DurationField): ...
class ACFRegexField(ACFFieldMixin, forms.RegexField): ...
class ACFEmailField(ACFFieldMixin, forms.EmailField): ...
class ACFFileField(ACFFieldMixin, forms.FileField): ...
class ACFImageField(ACFFieldMixin, forms.ImageField): ...
class ACFURLField(ACFFieldMixin, forms.URLField): ...
class ACFBooleanField(ACFFieldMixin, forms.BooleanField): ...
class ACFNullBooleanField(ACFFieldMixin, forms.NullBooleanField): ...
class ACFChoiceField(ACFFieldMixin, forms.ChoiceField): ...
class ACFTypedChoiceField(ACFFieldMixin, forms.TypedChoiceField): ...
class ACFMultipleChoiceField(ACFFieldMixin, forms.MultipleChoiceField): ...
class ACFTypedMultipleChoiceField(ACFFieldMixin, forms.TypedMultipleChoiceField): ...
class ACFComboField(ACFFieldMixin, forms.ComboField): ...
class ACFMultiValueField(ACFFieldMixin, forms.MultiValueField): ...
class ACFFilePathField(ACFFieldMixin, forms.FilePathField): ...
class ACFSplitDateTimeField(ACFFieldMixin, forms.SplitDateTimeField): ...
class ACFGenericIPAddressField(ACFFieldMixin, forms.GenericIPAddressField): ...
class ACFSlugField(ACFFieldMixin, forms.SlugField): ...
class ACFUUIDField(ACFFieldMixin, forms.UUIDField): ...
class ACFJSONField(ACFFieldMixin, forms.JSONField): ...
class ACFCurrencyField(ACFFieldMixin, forms.FloatField): ...
class ACFTextareaField(type, ACFFieldMixin, forms.CharField): ...
class ACFPhoneNumberField(ACFFieldMixin, forms.CharField): ...
class ACFCalculatedField(ACFFieldMixin, forms.CharField): ...
class ACFCalcualtedCurrencyField(ACFFieldMixin, forms.CharField): ...
class ACFFieldFilterField(ACFFieldMixin, forms.MultipleChoiceField): ...
class ACFYesNoDisplayField(ACFFieldMixin, forms.MultiValueField): ...

class ACFBoundFieldFilterField(forms.BoundField):
    def get_fields_to_exclude(self) -> list[str]: ...

class acf_fields(metaclass=ACFFieldsMeta):

    BooleanField: type[ACFBooleanField]
    CharField: type[ACFCharField]
    ChoiceField: type[ACFChoiceField]
    ComboField: type[ACFComboField]
    DateField: type[ACFDateField]
    DateTimeField: type[ACFDateTimeField]
    DecimalField: type[ACFDecimalField]
    DurationField: type[ACFDurationField]
    EmailField: type[ACFEmailField]
    Field: type[ACFField]
    FileField: type[ACFFileField]
    FilePathField: type[ACFFilePathField]
    FloatField: type[ACFFloatField]
    GenericIPAddressField: type[ACFGenericIPAddressField]
    ImageField: type[ACFImageField]
    IntegerField: type[ACFIntegerField]
    JSONField: type[ACFJSONField]
    MultiValueField: type[ACFMultiValueField]
    MultipleChoiceField: type[ACFMultipleChoiceField]
    NullBooleanField: type[ACFNullBooleanField]
    RegexField: type[ACFRegexField]
    SlugField: type[ACFSlugField]
    SplitDateTimeField: type[ACFSplitDateTimeField]
    URLField: type[ACFURLField]
    UUIDField: type[ACFUUIDField]
    CurrencyField: type[ACFCurrencyField]
    TextareaField: ACFTextareaField
    PhoneNumberField: type[ACFPhoneNumberField]
    CalculatedField: type[ACFCalculatedField]
    CalculatedCurrencyField: type[ACFCalcualtedCurrencyField]
    FieldFilterField: type[ACFFieldFilterField]
    YesNoDisplayField: type[ACFYesNoDisplayField]
