# Should have value.yaml plus the following:
fullnameOverride: csfeer-dev
replicaCount: 2

image:
  tag: FILL IN

staticImage:
  tag: FILL IN

mockImage:
  tag: 3a4ff2dd

service:

  # App service configuration
  app:
    scheme: internal
    subnets:
      - FILL IN 
    enableSSL: false # We don't need SSL for dev 
    loadBalancerLoggingBucket: csfeer-dev-loadbalancer-logging

configMap:
  shared:
    ENVIRONMENT: "dev"
    ALLOWED_HOSTS: '["*", "0.0.0.0"]'
    USE_DEV_LOGGING: "True"

  # Dev-specific database
  app:
    DB_CONFIG__PGHOST: "FILL IN"
    DEBUG: "True"
    OIDC_CONFIG__DOCUMENT_URL: FILL IN

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: FILL IN

dbMigrateJob:
  serviceAccount:
    roleArn: FILL IN

externalSecrets:
  # App-specific secrets
  apiSecretKeyArn: FILL IN
  oidcClientSecretArn: FILL IN
