# Common configurations
replicaCount: 2
# Override the name prefix for all resources. The chart name is different than the application name so thats why we need this
nameOverride: csfeer

# Common image settings
app:
  pullPolicy: Always
  repository: FILL IN

staticImage:
  pullPolicy: Always
  repository: FILL IN

# Python shell configuration
pythonShell:
  enabled: true
  repository: FILL IN
  tag: 3.12.10-slim
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      memory: 256Mi

# Mock server configuration
mockImage:
  repository: FILL IN
  pullPolicy: IfNotPresent
  deploy: true
  replicaCount: 2
  service:
    type: ClusterIP
    port: 8080
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      memory: 512Mi

# App API service configuration
service:

  app:
    type: ClusterIP
    targetPort: 8080
    enableSSL: false
    deletionProtectionEnabled: true

# Common variables passed to containers via ConfigMap
configMap:
  shared:
    AWS_REGION: us-east-1
    USE_DEV_LOGGING: "False"
    SECURE_SESSION_COOKIE: "True"
    DB_CONFIG__PGPORT: "5432"
    DB_CONFIG__USE_IAM_AUTH: "True"

  app:
    DB_CONFIG__PGDATABASE: "csfeer"
    DB_CONFIG__PGUSER: "csfeer_app_user"

  

# Common resources
resources:
  requests:
    cpu: 200m
    memory: 1Gi
  limits:
    memory: 1Gi

# Common HPA config
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 80

# Common service account
serviceAccount:
  create: true

# Common db migrate job
dbMigrateJob:
  enabled: true
  env:
    db_migrate_user_app: "csfeer_migration_user"
  resources:
    requests:
      cpu: 200m
      memory: 1Gi
    limits:
      memory: 1Gi

# Common RBAC
rbac:
  create: true

# Common external secrets
externalSecrets:
  region: us-east-1
