name: Run Tests

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  # push:
  #   branches: [main]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build --target prod-e2e -t csfeer:ci .

      - name: Run unit tests
        run: |
          export KC_SETUP_DELAY=60
          sudo bash -c "echo '127.0.0.1   oauth.csfeer' >> /etc/hosts"
          sudo bash -c "echo '127.0.0.1   ui.csfeer' >> /etc/hosts"
          mkdir -p tests/videos && chmod 777 tests/videos
          mkdir -p tests/traces && chmod 777 tests/traces
          mkdir -p tests/screenshots && chmod 777 tests/screenshots
          make test-unit-ci IMAGE_NAME=csfeer:ci
        env:
          IMAGE_NAME: csfeer:ci

      - name: Run e2e tests
        run: |
          export KC_SETUP_DELAY=60
          sudo bash -c "echo '127.0.0.1   oauth.csfeer' >> /etc/hosts"
          sudo bash -c "echo '127.0.0.1   ui.csfeer' >> /etc/hosts"
          mkdir -p tests/videos && chmod 777 tests/videos
          mkdir -p tests/traces && chmod 777 tests/traces
          mkdir -p tests/screenshots && chmod 777 tests/screenshots
          make test-e2e-ci IMAGE_NAME=csfeer:ci
        env:
          IMAGE_NAME: csfeer:ci

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts
          path: |
            tests/screenshots/
            tests/videos/
            tests/traces/
          retention-days: 7

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/
          retention-days: 7

      - name: Docker logs on failure
        if: failure()
        run: IMAGE_NAME=csfeer:ci docker compose -f devops/docker/docker-compose-ci.yml logs