{{- if .Values.externalSecrets -}}
# Application secrets external secret
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "csfeer.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ include "csfeer.fullname" . }}-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: app-secrets
    creationPolicy: Owner
  data:
    - secretKey: api_secret_key
      remoteRef:
        key: {{ .Values.externalSecrets.apiSecretKeyArn }}
    - secretKey: oidc_client_secret
      remoteRef:
        key: {{ .Values.externalSecrets.oidcClientSecretArn }}
    - secretKey: auth_api_key
      remoteRef:
        key: {{ .Values.externalSecrets.authApiKeyArn }}
    - secretKey: case_api_key
      remoteRef:
        key: {{ .Values.externalSecrets.caseApiKeyArn }}
{{- end }} 